name: Update Tagged Versions

on:
  schedule:
    - cron: '0 3 */7 * *'
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'LizenzFass78851/armbian-builder'
    env:           
      GIT_USER: github-actions[bot]
      GIT_EMAIL: github-actions[bot]@users.noreply.github.com

    steps:
      - name: key
        id: key
        run: |
          export KEY="${GITHUB_WORKFLOW%-*}"
          echo "key=$KEY" >> $GITHUB_OUTPUT
          echo "################################################################" && bash -c "echo KEY=$KEY"

      - name: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git clone https://github-actions:$GITHUB_TOKEN@${GITHUB_SERVER_URL##*/}/$GITHUB_REPOSITORY.git $GITHUB_WORKSPACE --branch $GITHUB_REF_NAME --depth=1 --single-branch

      - name: Find latest tag (update build)
        id: update_build_find_latest
        uses: oprypin/find-latest-tag@v1
        with:
          repository: armbian/build
          releases-only: true
      - name: update build
        id: update_build
        run: |
          [ "${{ github.workflow }}" != "${{ steps.key.outputs.key }}" ] && c=5 || c=1
          
          LATEST_TAG=${{ steps.update_build_find_latest.outputs.tag }}
          
          echo "BUILD_VER: $LATEST_TAG"

          seq $c | while read x; do \
          [ -n "$LATEST_TAG" ] && [ "$LATEST_TAG" != "null" ] && echo 'patching file' && sed -i "s|^BUILD_VER=.*|BUILD_VER=\"$LATEST_TAG\"|g" $GITHUB_WORKSPACE/build.env; \
          done

          # Commit changes if any
          git add build.env
          git status
          git config --local user.name ${{ env.GIT_USER }}
          git config --local user.email ${{ env.GIT_EMAIL }}
          if ! git diff --cached --quiet; then
            git commit -m "feat: Update build version to ${LATEST_TAG}"
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
          git push origin $GITHUB_REF_NAME

      - name: trigger build workflow
        if: steps.update_build.outputs.updated == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run build.yml

