name: Update Tagged Versions

on:
  schedule:
    - cron: '0 3 */7 * *'
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'LizenzFass78851/armbian-builder'
    env:           
      GIT_USER: github-actions
      GIT_EMAIL: github-actions@github.com

    steps:
      - name: key
        id: key
        run: |
          export KEY="${GITHUB_WORKFLOW%-*}"
          echo "key=$KEY" >> $GITHUB_OUTPUT
          echo "################################################################" && bash -c "echo KEY=$KEY"

      - name: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git clone https://github-actions:$GITHUB_TOKEN@${GITHUB_SERVER_URL##*/}/$GITHUB_REPOSITORY.git $GITHUB_WORKSPACE --branch $GITHUB_REF_NAME --depth=1 --single-branch

      - name: update build
        env:
          API_URL: "https://api.github.com/repos/armbian/build/releases/latest"
        run: |
          [ "${{ github.workflow }}" != "${{ steps.key.outputs.key }}" ] && c=5 || c=1
          
          LATEST_TAG=$(curl -s $API_URL | jq -r .tag_name)
          
          echo "BUILD_VER: $LATEST_TAG"

          seq $c | while read x; do \
          [ -n "$LATEST_TAG" ] && echo 'patching file' && sed -i "s|^BUILD_VER=.*|BUILD_VER=\"$LATEST_TAG\"|g" $GITHUB_WORKSPACE/build.env; \
          done

          # Commit changes if any
          git add build.env
          git status
          git config --local user.name ${{ env.GIT_USER }}
          git config --local user.email ${{ env.GIT_EMAIL }}
          git diff --cached --quiet && exit 0 || git commit -m "feat: Update build version to ${LATEST_TAG}"

      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
          git push origin $GITHUB_REF_NAME

